// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abkpixzxbulcmdmaueko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFia3BpeHp4YnVsY21kbWF1ZWtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjE0OTIsImV4cCI6MjA2NjMzNzQ5Mn0.7RgT8JvkSvNPa8SlFdQLMKqVXu4k4oznQ5Me_s0T_4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);